### ISSUE TITLE
How using ConversationStarted func

### ISSUE THREAD

**Issue by evgarik** [mileusna/viber#3]
Tell me please...

**Comment by mikivujkovic** [comment]
```
package main

import (
    "fmt"
    "log"
    "net/http"
    "time"

    "github.com/mileusna/viber"
)

func main() {
    v := &viber.Viber{
        AppKey: "YOUR-APP-KEY-FROM-VIBER",
        Sender: viber.Sender{
            Name:   "MyPage",
            Avatar: "https://mysite.com/img/avatar.jpg",
        },
        Message:   myMsgReceivedFunc,  // your function for handling messages
        Delivered: myDeliveredFunc,    // your function for delivery report
        ConversationStarted: convStartedFunc // ADD THIS LINE TO DEFINE WHICH FUNCTION HANDLES CONVERSATION STARTED
    }
    v.Seen = mySeenFunc   // or assign events after declaration
    
    // this have to be your webhook, pass it your viber app as http handler
    http.Handle("/viber/webhook/", v)
    http.ListenAndServe(":80", nil)    
}

// myMsgReceivedFunc will be called everytime when user send us a message
func myMsgReceivedFunc(v *viber.Viber, u viber.User, m viber.Message, token uint64, t time.Time) {
    switch m.(type) {

    case *viber.TextMessage:
        v.SendTextMessage(u.ID, "Thank you for your message")
        txt := m.(*viber.TextMessage).Text
        v.SendTextMessage(u.ID, "This is the text you have sent to me "+txt)

    case *viber.URLMessage:
        url := m.(*viber.URLMessage).Media
        v.SendTextMessage(u.ID, "You have sent me an interesting link "+url)

    case *viber.PictureMessage:
        v.SendTextMessage(u.ID, "Nice pic!")

    }
}

func myDeliveredFunc(v *viber.Viber, userID string, token uint64, t time.Time) {
    log.Println("Message ID", token, "delivered to user ID", userID)
}

func mySeenFunc(v *viber.Viber, userID string, token uint64, t time.Time) {
    log.Println("Message ID", token, "seen by user ID", userID)
}

// ADD THIS FUNCTION TO HANDLE CONVERSATION STARTED EVENT
func convStartedFunc(v *viber.Viber, u viber.User, conversationType, context string, subscribed bool, token uint64, t time.Time) viber.Message {
    return NewTextMessage("Thank you for subscribing")
}
```

**Comment by mileusna** [comment]
Thank you Miodrag for replying, I have forgotten about this question here.

Evgarik, as I mentioned in README, this package stick close to Viber API where _conversation_started_ event is described as:

> This event is not considered a subscribe event and doesn’t allow the account to send messages to the user; however, it will allow sending one “welcome message” to the user. See sending a welcome message below for more information.

So you can't just send regular messages from ConversationStarted function, you can just **return** **one** Message from the function which will be delivered to the user as the "welcome message".

More from Viber API doc: https://developers.viber.com/docs/api/rest-bot-api/#conversation-started

**Comment by mikivujkovic** [comment]
Miloš, thank you for writing this library. It has saved me a lot of time since this is the only complete Go wrapper against the Viber API. 

Evgarik: just wanted to add that this is a very useful function because it gives you the context field. 
I often use context to differentiate between users (via custom invitations) and to initialize state.
Since you have one message to send, you can attach a custom keyboard to it and help users to start interacting with you.

**Comment by mileusna** [comment]
Evgarik, also note that you have to call SetWebhook() with **nil** value for eventTypes param or to specify _conversation_started_ in the eventTypes slice of SetWebhook() call to be able to receive ConversationStarted event. You call SetWebhook() only once, or when you wish to change the params.

https://github.com/mileusna/viber#webhook

I hope that we have covered all possible issues that can cause you troubles with ConversationStarted event.

**Comment by evgarik** [comment]
Thanks all.
